# Package

version       = "0.1.0"
author        = "Joey Yakimowich-Payne"
description   = "Autogenerated glew bindings for Nim"
license       = "MIT"
srcDir        = "src"



# Dependencies

requires "nim >= 1.0.6", "https://github.com/jyapayne/nimterop#367ec05"
